import asyncio
import json
from abc import ABC, abstractmethod
from datetime import UTC, datetime

from suraj_dada.config.loader import Settings, get_config
from suraj_dada.logging_setup import get_logger

logger = get_logger("llm.client")


class LlmClient(ABC):
    @abstractmethod
    async def generate(self, prompt: str, max_tokens: int, temperature: float) -> str: ...

    @abstractmethod
    async def health_check(self) -> bool: ...


class MockLlmClient(LlmClient):
    def __init__(self, config: Settings | None = None):
        self._config = config or get_config()
        self._simulated_latency = 0.5
        self._call_count = 0

    async def generate(self, prompt: str, max_tokens: int, temperature: float) -> str:
        self._call_count += 1
        start = datetime.now(UTC)
        await asyncio.sleep(self._simulated_latency)
        elapsed = (datetime.now(UTC) - start).total_seconds()
        logger.info(
            "MockLlmClient.generate called",
            extra={
                "call_count": self._call_count,
                "prompt_length": len(prompt),
                "max_tokens": max_tokens,
                "temperature": temperature,
                "duration_ms": round(elapsed * 1000),
            },
        )

        if "practice" in prompt.lower() or "question" in prompt.lower():
            return json.dumps(
                {
                    "questions": [
                        {
                            "id": 1,
                            "question_text": "Sample question generated by mock LLM",
                            "options": {
                                "A": "Option 1",
                                "B": "Option 2",
                                "C": "Option 3",
                                "D": "Option 4",
                            },
                            "difficulty": 3,
                            "hint": "Review the relevant formula.",
                            "concept_reference": "general",
                        }
                    ]
                }
            )

        if "explain" in prompt.lower():
            return "This is a mock explanation. The correct concept involves understanding the underlying principles and applying the appropriate formula."  # noqa: E501

        if "hint" in prompt.lower():
            return "Review the formula and try breaking the problem into smaller steps."

        return json.dumps({"response": "Mock LLM response"})

    async def health_check(self) -> bool:
        await asyncio.sleep(0.1)
        logger.info("MockLlmClient health check passed")
        return True
