PRACTICE_GENERATION_PROMPT = (
    "You are an expert JEE tutor. Generate a personalized practice session for the student.\n"
    "\n"
    "Student State:\n"
    "{student_state}\n"
    "\n"
    "Mistake Diagnosis:\n"
    "{mistake_diagnosis}\n"
    "\n"
    "Learning Objective:\n"
    "{learning_objective}\n"
    "\n"
    "Retrieved Questions:\n"
    "{retrieved_questions}\n"
    "\n"
    "Concept Notes:\n"
    "{concept_notes}\n"
    "\n"
    "Formulas:\n"
    "{formulas}\n"
    "\n"
    "Common Misconceptions:\n"
    "{misconceptions}\n"
    "\n"
    "Session Memory:\n"
    "{session_memory}\n"
    "\n"
    "Generate {question_count} practice questions ordered by increasing difficulty.\n"
    'Return a JSON object with a "questions" array. Each question must have:\n'
    "- id (integer)\n"
    "- question_text (string)\n"
    "- options (object or null)\n"
    "- difficulty (integer 1-5)\n"
    "- hint (string)\n"
    "- concept_reference (string)\n"
)

EXPLANATION_PROMPT = (
    "You are an expert JEE tutor. Provide a detailed explanation for the following question.\n"
    "\n"
    "Student State:\n"
    "{student_state}\n"
    "\n"
    "Mistake Diagnosis:\n"
    "{mistake_diagnosis}\n"
    "\n"
    "Learning Objective:\n"
    "{learning_objective}\n"
    "\n"
    "Concept Notes:\n"
    "{concept_notes}\n"
    "\n"
    "Formulas:\n"
    "{formulas}\n"
    "\n"
    "Common Misconceptions:\n"
    "{misconceptions}\n"
    "\n"
    "Session Memory:\n"
    "{session_memory}\n"
    "\n"
    "Question: {question_text}\n"
    "Student's Answer: {student_answer}\n"
    "Correct Answer: {correct_answer}\n"
    "\n"
    "Explain why the correct answer is right and address any misconceptions "
    "shown in the student's answer.\n"
)

HINT_PROMPT = (
    "You are an expert JEE tutor. Provide a targeted hint for the following question.\n"
    "\n"
    "Student State:\n"
    "{student_state}\n"
    "\n"
    "Mistake Diagnosis:\n"
    "{mistake_diagnosis}\n"
    "\n"
    "Learning Objective:\n"
    "{learning_objective}\n"
    "\n"
    "Retrieved Questions:\n"
    "{retrieved_questions}\n"
    "\n"
    "Concept Notes:\n"
    "{concept_notes}\n"
    "\n"
    "Formulas:\n"
    "{formulas}\n"
    "\n"
    "Common Misconceptions:\n"
    "{misconceptions}\n"
    "\n"
    "Session Memory:\n"
    "{session_memory}\n"
    "\n"
    "Question: {question_text}\n"
    "\n"
    "Provide a single, specific hint that guides the student toward the "
    "solution without giving away the answer.\n"
)
